name: null
favicon: null
layout_spectrum: 0.65789
typography_spectrum: 0.27193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0f16'
    - '#3d2f2b'
    - '#6e6461'
    - '#b6c7ff'
    - '#fff8ff'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
